# Generated by Django 5.1 on 2024-09-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('enName', models.CharField(max_length=100, verbose_name='англ имя')),
                ('role', models.CharField(choices=[('actor', 'актер'), ('director', 'режиссер'), ('writer', 'сценарист')], max_length=100, verbose_name='роль')),
            ],
            options={
                'verbose_name': 'персона',
                'verbose_name_plural': 'персоны',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('enName', models.CharField(max_length=100, verbose_name='англ название')),
                ('description', models.TextField(verbose_name='описание')),
                ('year', models.IntegerField(verbose_name='год')),
                ('madeIn', models.CharField(max_length=100, verbose_name='страна')),
                ('ageLimit', models.IntegerField(verbose_name='возрастное ограничение')),
                ('rating', models.FloatField(verbose_name='рейтинг imdb')),
                ('movieLength', models.IntegerField(verbose_name='длительность')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='постер')),
                ('premier', models.DateField(verbose_name='премьера')),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('not_published', 'Не опубликован'), ('draft', 'Черновик'), ('deleted', 'Удален')], default='draft', max_length=100, verbose_name='статус')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='жанры')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'актер'), ('director', 'режиссер'), ('writer', 'сценарист')], max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(related_name='movies', through='movies.PersonMovie', to='movies.person', verbose_name='персоны'),
        ),
    ]
