# Generated by Django 5.1 on 2024-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('not_published', 'Не опубликован'), ('draft', 'Черновик'), ('deleted', 'Удален')], default='draft', max_length=100, verbose_name='статус'),
        ),
    ]
