# Generated by Django 5.0.6 on 2024-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('enName', models.CharField(max_length=100, verbose_name='англ имя')),
                ('role', models.CharField(choices=[('actor', 'актер'), ('director', 'режиссер'), ('writer', 'сценарист')], max_length=100, verbose_name='роль')),
            ],
            options={
                'verbose_name': 'персона',
                'verbose_name_plural': 'персоны',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('enName', models.CharField(max_length=100, verbose_name='англ название')),
                ('description', models.TextField(verbose_name='описание')),
                ('year', models.IntegerField(verbose_name='год')),
                ('madeIn', models.CharField(max_length=100, verbose_name='страна')),
                ('ageLimit', models.IntegerField(verbose_name='возрастное ограничение')),
                ('rating', models.FloatField(verbose_name='рейтинг imdb')),
                ('movieLength', models.IntegerField(verbose_name='длительность')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='постер')),
                ('premier', models.DateField(verbose_name='премьера')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='жанры')),
                ('persons', models.ManyToManyField(to='movies.person', verbose_name='персоны')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
